#!/usr/bin/node

let fs = require("fs");
let Phrase = require("aadigamov-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
let arrayForFile = [];

text.split("\n").forEach(function(line) {
	let phrase  = new Phrase(line);
	if (phrase.palindrome()) {
		console.log("palindrome detected:", line);
		arrayForFile.push(line)
	}
});

fs.writeFileSync("palindromes.txt", arrayForFile.join("\n"));
		